<a href="https://colab.research.google.com/github/laura314159265/poly/blob/main/PR%C3%80CTICA_GUIADA/M%C3%88TODES_COR_PROGRAMA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Partim de la EDP:


$c_vρ\frac{∂T}{∂t}=∇⋅(κ{\vec\nabla T})+P_{ext}$

Després de normalitzar i reduïr els paràmetres al mínim obtenim:

$\frac{\partial\tilde{T}}{\partial\tilde{t}}=\frac{\partial^2\tilde{T}}{\partial\tilde{x}^2}+1$



Discretitzem via Euler explícit amb la derivada per la dreta:

$\frac{T_{i+1}^{(n)}-T_i^{(n)}}{Δt}=1+\frac{T_i^{(n+1)}-2T_i^{(n)}+T_i^{(n-1)}}{(Δx)^2}$

Aïllem $T_{i+1}^{(n)}$:

$T_{i+1}^{(n)}=Δt+\alpha T_{i}^{(n-1)}+βT_{i}^{(n)} + α T_{i}^{(n+1)}$

On: $\ α=\frac{Δt}{\Delta x^2},\ β=1-\frac{2\Delta t}{\Delta x^2}$

Això es pot escriure en forma matricial i calcular tots els punts espaials de la malla a temps $i+1$ a partir dels de i. Ja que tenim tots els punts de $i=0$ de les condicions de contorn

I les condicions de contorn són:

*   $T(0,x)=36,5\ ℃$
*   $\frac{\partial T(t,\ 0)}{\partial t}=\frac{\partial T(t,\ 2\ cm)}{\partial t}=0$



In [118]:
#EULER EXPLÍCIT

import numpy as np
from scipy.linalg import toeplitz
import matplotlib.pyplot as plt

#Dades de l'enunciat
C_v= 3686
rho= 1081
kappa= 0.56
sigma= 0.472
volts= 40

N= 101   # Mallat espaial

x_0= 0.02
x_f= 0.02/x_0
x_i= 0

alpha_var= kappa/(C_v*rho)
print("La difusivitat dona:", alpha_var)

t_i= 0
t_0= x_0**2/alpha_var
print("t_0 és:", t_0)
t_f= 0.025
print("t_f és:", t_f)

#Variacions de les variables (els tres delta t corresponen als 3 de l'enunciat)
dx= x_f/N
print("El dx és:", dx)
dt_1= 0.51*dx**2 # disc temps 1
print("dt_1 és:", dt_1)
dt_2= 0.49*dx**2 # disc temps 2
dt_3= 0.25*dx**2  # disc temps 3

alpha= dt_1/(dx**2)
beta= 1-2*dt_1/(dx**2)

P_ext= volts**2*sigma/(2*(x_0)**2)
print(P_ext)

T_0= P_ext/(C_v*rho)*t_0
print("T_0 val:", T_0)
T_init= 36.5/T_0   #Temperatura inicial
print("T_init:",T_init)
T_i= np.ones((N-2,1))*T_init  #Vector columna de les T_i per cada n (punt de l'espai)
deltat= np.ones((N-2,1))*dt_1 #Vector columna de Δt per sumar a l'expressió

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#Creació de la matriu
col1= [0]*(N-2)
col1[0]= beta
col1[1]= alpha
fila1= [0]*(N-2)
fila1[1]= alpha

matriu= toeplitz(col1, fila1) #Funció que crea una matriu diagonal per blocs a
                              #partir de la primera columna i la primera fila
print(matriu)
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
vec_aux= np.zeros((N-2,1))
vec_aux[0,0]= T_init*alpha
vec_aux[-1,0]= T_init*alpha
print(len(vec_aux))
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

La difusivitat dona: 1.405422823966274e-07
t_0 és: 2846.1185714285716
t_f és: 0.025
El dx és: 0.009900990099009901
dt_1 és: 4.999509851975297e-05
943999.9999999999
T_0 val: 674.2857142857143
T_init: 0.05413135593220338
[[-0.02  0.51  0.   ...  0.    0.    0.  ]
 [ 0.51 -0.02  0.51 ...  0.    0.    0.  ]
 [ 0.    0.51 -0.02 ...  0.    0.    0.  ]
 ...
 [ 0.    0.    0.   ... -0.02  0.51  0.  ]
 [ 0.    0.    0.   ...  0.51 -0.02  0.51]
 [ 0.    0.    0.   ...  0.    0.51 -0.02]]
99


Bloc del càlcul amb Euler explícit:

In [120]:
#EULER CÀLCUL
def Euler_explícit (T_i, t_f, dt, dx):
  i=1
  t_i=0
  x_i=0
  while t_i<t_f:

    T_i= np.matmul(matriu,T_i)+vec_aux+deltat
    t_i= t_i + dt
    x_i= x_i + dx

    #print(t_i)
    i=i+1
  print(f"El resultat de la iteració {i} és", T_i*T_0)
  return T_i
  """
  inputs: T_i (array de les temperatures inicials),
  t_f (temps final),
  dt (variació de temps),
  dx (varticaió d'espai)
  """

print(len(Euler_explícit(T_i, t_f, dt_1, dx)))
Euler_explícit(T_i, t_f, dt_2, dx)
Euler_explícit(T_i, t_f, dt_3, dx)

El resultat de la iteració 502 és [[  141.08010336]
 [ -167.46125911]
 [  347.56314151]
 [ -366.71768662]
 [  546.44777529]
 [ -556.50413378]
 [  733.18105792]
 [ -732.45248053]
 [  903.6953756 ]
 [ -890.76310722]
 [ 1054.56549585]
 [-1028.34608049]
 [ 1183.13171023]
 [-1142.92536099]
 [ 1287.5836088 ]
 [-1233.10186624]
 [ 1367.00167236]
 [-1298.37393937]
 [ 1421.35659472]
 [-1339.11645593]
 [ 1451.46882868]
 [-1356.52223441]
 [ 1458.93308634]
 [-1352.51141853]
 [ 1446.01425704]
 [-1329.61593896]
 [ 1415.5223309 ]
 [-1290.84696197]
 [ 1370.67438653]
 [-1239.55338119]
 [ 1314.95153788]
 [-1179.27895203]
 [ 1251.95800934]
 [-1113.62470534]
 [ 1185.2883413 ]
 [-1046.1219441 ]
 [ 1118.40726965]
 [ -980.11958474]
 [ 1054.54523842]
 [ -918.68801921]
 [  996.61095759]
 [ -864.54020118]
 [  947.12105317]
 [ -819.96943126]
 [  908.14578923]
 [ -786.80242752]
 [  881.26914674]
 [ -766.36577355]
 [  867.56125292]
 [ -759.46374303]
 [  867.56125292]
 [ -766.36577355]
 [  881.26914673]
 [ -786.8024

array([[ 4.25605258e+07],
       [-8.50296669e+07],
       [ 1.27316570e+08],
       [-1.69331438e+08],
       [ 2.10986049e+08],
       [-2.52194258e+08],
       [ 2.92872489e+08],
       [-3.32940190e+08],
       [ 3.72320283e+08],
       [-4.10939568e+08],
       [ 4.48729100e+08],
       [-4.85624535e+08],
       [ 5.21566431e+08],
       [-5.56500508e+08],
       [ 5.90377874e+08],
       [-6.23155194e+08],
       [ 6.54794822e+08],
       [-6.85264884e+08],
       [ 7.14539312e+08],
       [-7.42597830e+08],
       [ 7.69425901e+08],
       [-7.95014616e+08],
       [ 8.19360551e+08],
       [-8.42465567e+08],
       [ 8.64336583e+08],
       [-8.84985300e+08],
       [ 9.04427892e+08],
       [-9.22684666e+08],
       [ 9.39779689e+08],
       [-9.55740390e+08],
       [ 9.70597140e+08],
       [-9.84382810e+08],
       [ 9.97132320e+08],
       [-1.00888217e+09],
       [ 1.01966998e+09],
       [-1.02953400e+09],
       [ 1.03851265e+09],
       [-1.04664406e+09],
       [ 1.0