<a href="https://colab.research.google.com/github/laura314159265/poly/blob/main/PR%C3%80CTICA_GUIADA/P1_EULER_IMPLICIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

hola implícit és com l'explícit però derivant per l'esquerra en lloc de per la dreta

he aïllat i han passat coses i em queda:

$\vec{T_i}=M^{-1}(\vec{T_{i-1}}+\vec{\Delta t})$

$M\vec{T_i}=\vec{T_{i-1}}+\vec{\Delta t}$

(són el mateix)

In [28]:
#PRIMER CALCULEM LA MATRIU M
import numpy as np
from numpy.linalg import inv
from scipy.linalg import toeplitz
import matplotlib.pyplot as plt

N= 101   # Mallat espaial, nombre de punts que tenim

x_0= 0.02 #per la cara
x_f= 0.02/x_0 #normalitzar, ja que \tilde{x}=x/x_0
x_i= 0

t_i= 0
t_0= x_0**2/alpha_var #\tilde{t}=t/t_0
t_f= 0.025 #ja està normalitzat, ho diu l'enunciat

#Variacions de les variables (tenim dos casos a l'enunciat)
dx= x_f/(N-1) #lol
print("dx=",dx)
dt_1= dx**2 # disc temps 1
dt_2= 0.5*dx**2 # disc temps 2

#CAS GENERAL PER A QUALSEVOL dx, dt:
def matriu(dt,dx):
  alpha= -dt/(dx**2) #ALFA I BETA SÓN DIFERENTS A L'IMPLÍCIT I A L'EXPLÍCIT LOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLLLOLOLOLOLOLOLOL
  beta= 1+2*dt/(dx**2)
  #Creació de la matriu
  col1= [0]*(N)
  col1[0]= beta
  col1[1]= alpha
  fila1= [0]*(N)
  fila1[1]= alpha
  matriu = toeplitz(col1, fila1)
  return matriu

matriu_1=matriu(dt_1,dx)
matriu_2=matriu(dt_2,dx)
print(matriu_1)
print(matriu_2)

dx= 0.01
[[ 3. -1.  0. ...  0.  0.  0.]
 [-1.  3. -1. ...  0.  0.  0.]
 [ 0. -1.  3. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  3. -1.  0.]
 [ 0.  0.  0. ... -1.  3. -1.]
 [ 0.  0.  0. ...  0. -1.  3.]]
[[ 2.  -0.5  0.  ...  0.   0.   0. ]
 [-0.5  2.  -0.5 ...  0.   0.   0. ]
 [ 0.  -0.5  2.  ...  0.   0.   0. ]
 ...
 [ 0.   0.   0.  ...  2.  -0.5  0. ]
 [ 0.   0.   0.  ... -0.5  2.  -0.5]
 [ 0.   0.   0.  ...  0.  -0.5  2. ]]


In [29]:
#ja coneixem la matriu M que té a la diagonal beta envoltada de alpha
#EULER CÀLCUL

def Euler_implicit (T_i, t_f, dt, dx):
    i=1
    t_i=0
    x_i=0
    while t_i<t_f:
      if dt==dt_1:
        T_i = np.matmul(inv(matriu_1), (T_i + np.ones((N,1))*dt))
      elif dt==dt_2:
        T_i = np.matmul(inv(matriu_2), (T_i + np.ones((N,1))*dt))
      else:
        print("no ho puc resoldre perquè no m'has donat quina matriu M haig de fer servir")
      t_i = t_i + dt
      x_i = x_i + dx
      i = i + 1
    # print(f"El resultat de la iteració {i} és", T_i*T_0)
    return T_i   # <-- IMPORTANT per poder calcular després la temperatura real


#recordem que les nostres dades són
    #ENUNCIAT:
C_v= 3686
rho= 1081
kappa= 0.56
sigma= 0.472
volts= 40
    #COSES CALCULADES:
alpha_var= kappa/(C_v*rho)
P_ext= volts**2*sigma/((x_0)**2) #calculada per anàlisi dimensional a partir de dades proporcionades
T_0= P_ext/(C_v*rho)*t_0
print("T_0=",T_0)
T_init= 309.65/T_0   #CREC QUE HA D'ESTAR EN KELVIN PER LES UNITATS YOQUESE
print("T_init=",T_init)
T_init_vec= np.ones((N,1))*T_init

#i apliquem la funció que hem creat als nostres dos casos de discretitzacions
resultat_1 = Euler_implicit(T_init_vec, t_f, dt_1, dx)
resultat_2 = Euler_implicit(T_init_vec, t_f, dt_2, dx)


#temperatura real (kelvin)
T_real_1 = resultat_1 * T_0
T_real_2 = resultat_2 * T_0

print("Temperatura real cas 1 (Kelvin):")
print(T_real_1)

print("Temperatura real cas 2 (Kelvin):")
print(T_real_2)


T_0= 1348.5714285714287
T_init= 0.2296133474576271
Temperatura real cas 1 (Kelvin):
[[ 13.3827471 ]
 [ 26.61330007]
 [ 39.67444481]
 [ 52.54921169]
 [ 65.22099456]
 [ 77.67366584]
 [ 89.89168665]
 [101.8602107 ]
 [113.56518099]
 [124.99341832]
 [136.13270079]
 [146.97183366]
 [157.50070877]
 [167.71035335]
 [177.59296762]
 [187.14195125]
 [196.35191844]
 [205.21870181]
 [213.73934534]
 [221.91208659]
 [229.73632873]
 [237.21260293]
 [244.34252172]
 [251.12872397]
 [257.57481244]
 [263.68528455]
 [269.46545733]
 [274.92138742]
 [280.05978702]
 [284.88793665]
 [289.41359574]
 [293.64491169]
 [297.59032847]
 [301.25849539]
 [304.65817686]
 [307.79816387]
 [310.68718768]
 [313.33383655]
 [315.74647581]
 [317.9331719 ]
 [319.9016207 ]
 [321.65908057]
 [323.21231041]
 [324.56751292]
 [325.73028347]
 [326.70556451]
 [327.4976059 ]
 [328.10993113]
 [328.54530957]
 [328.80573484]
 [328.89240932]
 [328.80573484]
 [328.54530957]
 [328.10993113]
 [327.4976059 ]
 [326.70556451]
 [325.73028347]
 [32